# See <https://fly.io/docs/reference/configuration>

app = "kzg-ceremony-sequencer-369-dev"
kill_signal = "SIGINT"
kill_timeout = 30 # Seconds
processes = []

[build]
    image = "zyclonepunch/kzg-ceremony-sequencer:latest"

[[mounts]]
    source = "kzg_ceremony_seq_dev_369_data"
    destination = "/data"

[env]
    VERBOSE="3"
    GH_REDIRECT_URL="https://kzg-ceremony-sequencer-369-dev.fly.dev/auth/callback/github"
    ETH_REDIRECT_URL="https://kzg-ceremony-sequencer-369-dev.fly.dev/auth/callback/eth"
    ETH_MIN_NONCE="0"
    MULTI_CONTRIBUTION="true"
    COMPUTE_DEADLINE="480"
    LOBBY_CHECKIN_FREQUENCY="30"
    LOBBY_CHECKIN_TOLERANCE="15"

# ❯ fly secrets list
# NAME                    DIGEST                  CREATED AT
# ETH_CLIENT_ID           490c65a6cd74f540        2025-01-16T17:49:00Z
# ETH_CLIENT_SECRET       4bde0a26e498b89a        2025-01-16T17:49:00Z
# ETH_RPC_URL             22aa2020cdb847b8        2025-01-16T17:49:00Z
# GH_CLIENT_ID            c45b86b2685ea585        2025-01-16T17:49:00Z
# GH_CLIENT_SECRET        6c82c79e465bf69b        2025-01-16T17:49:00Z

[experimental]
    allowed_public_ports = []
    auto_rollback = true

[metrics]
    # Prometheus metrics server. See PROMETHEUS env var.
    port = 9998
    path = "/metrics"

[[services]]
    internal_port = 8080
    protocol = "tcp"

    [[services.ports]]
        force_https = true
        handlers = ["http"]
        port = 80

    [[services.ports]]
        handlers = ["tls", "http"]
        port = 443
